"""Generate an "AMD TCO & Procurement ROI" markdown proposal.

Grounds the C-level narrative in the *deterministic* gatekeeper math (so the
numbers are defensible) plus a published cost datapoint for uncontrolled
open-ended agent self-improvement (Darwin Gödel Machine: ~$22k / 2 weeks per
80-iteration run) to justify AgentForge's controlled, gatekeeper-pruned,
epoch-gated approach on on-prem AMD hardware.
"""

from __future__ import annotations

import math
from typing import Any

from backend.domains.base import WorkflowTemplate
from backend.gatekeeper.feasibility import Feasibility
from backend.gatekeeper.spec import ModelSpec, TierSpec

# Published datapoint for uncontrolled open-ended evolution (Darwin Gödel Machine).
DGM_COST_USD = 22_000
DGM_DURATION = "2 weeks"
DGM_ITERS = 80
DGM_COST_PER_ITER = DGM_COST_USD / DGM_ITERS  # ~= $275 / iteration

# Assumed cloud premium vs. amortized on-prem for an equivalent evolution run.
_ASSUMED_RUNS_PER_YEAR = 12
_HORIZON_YEARS = 3
_ANNUAL_OPEX_FRACTION = 0.15  # power/cooling/admin as a fraction of capex per year


def _fmt_usd(x: float | None) -> str:
    if x is None:
        return "n/a"
    return f"${x:,.0f}"


def _vram_bar(breakdown: dict[str, float], capacity_gb: float, width: int = 28) -> str:
    total = sum(breakdown.values())
    used = min(total, capacity_gb)
    filled = int(round(width * used / capacity_gb)) if capacity_gb > 0 else width
    filled = max(0, min(width, filled))
    return "[" + "#" * filled + "-" * (width - filled) + f"] {total:.1f} / {capacity_gb:.0f} GB"


def generate_tco_markdown(
    tier: TierSpec,
    model: ModelSpec,
    feasibility: Feasibility,
    template: WorkflowTemplate | None = None,
    domain_id: str | None = None,
    seq_len: int = 4096,
    concurrency: int = 1,
    dtype: str | None = None,
) -> str:
    dtype = dtype or model.dtype_default
    report = feasibility.to_dict()
    breakdown = report["vram_breakdown"]

    # ROI arithmetic (explicit + conservative).
    capex = tier.price_usd_est or 0.0
    annual_opex = capex * _ANNUAL_OPEX_FRACTION
    onprem_3yr = capex + annual_opex * _HORIZON_YEARS
    cloud_3yr = DGM_COST_USD * _ASSUMED_RUNS_PER_YEAR * _HORIZON_YEARS
    savings_3yr = cloud_3yr - onprem_3yr
    payback_runs = (capex / DGM_COST_USD) if DGM_COST_USD else 0.0

    feasible_str = "FEASIBLE" if feasibility.feasible else "NOT FEASIBLE"
    template_line = (
        f"- **Workflow template:** {template.name} — {template.description}"
        if template is not None
        else "- **Workflow template:** (none selected)"
    )

    md = f"""# AMD TCO & Procurement ROI Proposal

> Generated by **AgentForge** — a self-evolving AI-agent sizing platform on the
> AMD open-source ROCm stack. Sizing figures below are produced by the
> **deterministic Static Gatekeeper** (physics, non-negotiable), not by an LLM.

## 1. Executive summary

Deploying **{model.name}** ({dtype}) for **{domain_id or 'your domain'}** on the
**{tier.name}** ({tier.cls}) is **{feasible_str}** at seq_len={seq_len:,},
concurrency={concurrency}. This proposal recommends the AMD open-source stack
(ROCm + vLLM + Lemonade + Quark) to avoid per-seat license lock-in and to run
controlled agent self-evolution **on-prem** instead of paying the cloud premium
for uncontrolled open-ended search.

{template_line}

## 2. Recommended configuration

| Item | Value |
|---|---|
| Hardware tier | **{tier.name}** ({tier.cls}) |
| Memory | {tier.memory_gb:.0f} GB |
| Memory bandwidth | {tier.bandwidth_tbs:.3f} TB/s |
| Form factor | {tier.form_factor} |
| NPU | {"yes (~%.0f TOPS)" % tier.tops_npu if tier.has_npu and tier.tops_npu else "no"} |
| Est. unit price | {_fmt_usd(tier.price_usd_est)} |
| Model | {model.name} ({model.params_b:.1f}B params, {dtype}) |
| Context / concurrency | {seq_len:,} tokens / {concurrency} |

## 3. Deterministic sizing (verified by the Static Gatekeeper)

```
VRAM  {_vram_bar(breakdown, tier.memory_gb)}
```

| VRAM component | GB |
|---|---|
| Weights | {breakdown['weights']:.2f} |
| KV cache | {breakdown['kv_cache']:.2f} |
| Activations | {breakdown['activations']:.2f} |
| Framework overhead | {breakdown['overhead']:.2f} |
| **Total** | **{report['vram_total_gb']:.2f}** |
| Headroom on {tier.memory_gb:.0f} GB | **{report['headroom_gb']:.2f}** |

- **Decode throughput (est.):** ~{report['tokens_per_s_est']:.0f} tokens/s
  (memory-bandwidth bound: bandwidth / bytes-read-per-token).
- **Max population under prefix caching:** {report['max_population']:,} concurrent
  branches (MCTS / population search).
- **KV saved by prefix caching @ this concurrency:** {report['kv_savings_from_prefix_pct']:.1f}%.

> Physics is the trust foundation: these figures come from
> `VRAM = weights + KV + activations + overhead` and a memory-bandwidth decode
> bound. They do not evolve and cannot be argued away by a model.

## 4. Why the AMD open-source stack

- **ROCm** open compute platform — no proprietary runtime license.
- **vLLM (`rocm/vllm-dev`)** with `--enable-prefix-caching` for population/MCTS
  workloads; `VLLM_ROCM_USE_AITER=1` for AMD-optimized attention.
- **Lemonade** OpenAI-compatible local serving on Ryzen AI (NPU) / Radeon (ROCm).
- **AMD Quark** for int4/fp8 quantization (the {dtype} weights sized above).
- Large-VRAM Instinct parts (MI300X 192 GB / MI325X 256 GB) uniquely enable
  **persistent negative-result memory** + large populations that smaller 24–48 GB
  cards cannot hold resident.

## 5. The cost of *uncontrolled* evolution — and how we avoid it

A published open-ended self-improvement run (Darwin Gödel Machine) costs about
**{_fmt_usd(DGM_COST_USD)} over {DGM_DURATION} for {DGM_ITERS} iterations**
(~{_fmt_usd(DGM_COST_PER_ITER)}/iteration) in cloud compute. AgentForge cuts that
structurally:

1. **Deterministic gatekeeper prunes physically-infeasible candidates BEFORE any
   GPU spend** — rejected proposals cost $0 of accelerator time.
2. **Epoch-frozen evaluator + HITL-gated upgrades** stop redundant, drifting
   re-runs (RQGM controlled evolution, not open-ended burn).
3. **Selective erasure** keeps only useful memory, shrinking context/compute.

## 6. TCO & ROI ({_HORIZON_YEARS}-year horizon)

Assumptions: **{_ASSUMED_RUNS_PER_YEAR} evolution runs/year**, cloud priced at the
DGM datapoint per run, on-prem opex at {int(_ANNUAL_OPEX_FRACTION*100)}%/yr of capex.

| Option | 3-year cost |
|---|---|
| Cloud (uncontrolled, {_ASSUMED_RUNS_PER_YEAR}×/yr @ {_fmt_usd(DGM_COST_USD)}) | {_fmt_usd(cloud_3yr)} |
| On-prem **{tier.name}** (capex {_fmt_usd(capex)} + opex) | {_fmt_usd(onprem_3yr)} |
| **Estimated 3-year savings** | **{_fmt_usd(savings_3yr)}** |

- **Hardware payback:** ~{payback_runs:.1f} equivalent cloud runs to cover the
  {tier.name} unit price.

## 7. Procurement recommendation

**Recommended:** {tier.name} for {model.name} ({dtype}).
{"This configuration fits with headroom to spare — proceed." if feasibility.feasible else "This configuration does NOT fit — size up a tier (more VRAM) or quantize/reduce context before procurement."}

### Assumptions & caveats
- Prices are rough estimates (see tier notes) and vary by vendor/region/volume.
- Tier-4 Instinct figures are **simulated** via the gatekeeper (no physical MI300X/MI325X here).
- ROI assumes the stated run cadence; adjust `runs/year` to your roadmap.
- Sizing uses decimal-GB and a memory-bandwidth decode bound; real throughput
  depends on kernels, batching and prefix hit-rate.
"""
    return md
